services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yml
    volumes:
      - ./src/app/openApi/openapi.yml:/app/openapi.yml
    restart: always

  # swagger-codegen:
  #   image: swaggerapi/swagger-codegen-cli-v3
  #   container_name: swagger-codegen
  #   command: generate -i /local/openapi.yml -l typescript-fetch -o /local/out/typescript --additional-properties=typescriptThreePlus=true,supportsES6=true,nullableReferenceTypes=true
  #   volumes:
  #     - ./src/app/openApi:/local
  #     - ./src/types/autoFile:/local/out # 出力先ディレクトリを変更
  #   working_dir: /local
