"use client";

// import type { Metadata } from "next";
import { PrimeReactProvider, addLocale, locale } from "primereact/api";
import { SessionProvider } from "next-auth/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactNode, useState } from "react";
import { LocaleJp } from "../../utils/LocaleJp";
import { useEffectOnce } from "../..//hooks/CustomHooks";
import { Provider } from "jotai";
import { DevTools } from "jotai-devtools";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

addLocale("jp", LocaleJp);
locale("jp");

const queryClient = new QueryClient();

export default function Providers({ children }: { children: ReactNode }) {
  const [showScreen, setShowScreen] = useState(false);

  // FOUC対策
  useEffectOnce(() => {
    setShowScreen(true);
  });

  if (!showScreen) return null;

  return (
    <PrimeReactProvider>
      <SessionProvider>
        <QueryClientProvider client={queryClient}>
          <Provider>
            <DevTools />
            {children}
          </Provider>
        </QueryClientProvider>
      </SessionProvider>
    </PrimeReactProvider>
  );
}
