"use client";

// import type { Metadata } from "next";
import { PrimeReactProvider, addLocale, locale } from "primereact/api";
import "../styles/globals.css";
import "primereact/resources/themes/bootstrap4-light-blue/theme.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import "primereact/resources/primereact.min.css";
import { SessionProvider } from "next-auth/react";
import { useState } from "react";
import { useEffectOnce } from "./hooks/CustomHooks";
import { LocaleJp } from "./utils/LocaleJp";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // FOUC対策
  const [showScreen, setShowScreen] = useState(false);
  useEffectOnce(() => {
    setShowScreen(true);
  });

  // 日本語設定
  addLocale("jp", LocaleJp);

  locale("jp");

  // tanstack-query
  const queryClient = new QueryClient();

  return (
    <html lang="ja">
      <body>
        {showScreen && (
          <PrimeReactProvider>
            <SessionProvider>
              <QueryClientProvider client={queryClient}>
                {children}
              </QueryClientProvider>
            </SessionProvider>
          </PrimeReactProvider>
        )}
      </body>
    </html>
  );
}
