import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import "./globals.css";
import "primereact/resources/themes/bootstrap4-light-blue/theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <PrimeReactProvider>
        <body>{children}</body>
      </PrimeReactProvider>
    </html>
  );
}
