"use client";

import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import "../styles/globals.css";
import "primereact/resources/themes/bootstrap4-light-blue/theme.css";
import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import { SessionProvider } from "next-auth/react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <PrimeReactProvider>
        <SessionProvider>
          <body>{children}</body>
        </SessionProvider>
      </PrimeReactProvider>
    </html>
  );
}
