name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # チェックアウトリポジトリ
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Dockerのセットアップ
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Docker Composeのインストール
      - name: Install Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Docker Composeを使って依存関係をインストール
      - name: Build Docker Compose Services
        run: docker-compose build

      # Docker Composeを使ってLintを実行
      - name: Run Lint in Docker
        run: docker-compose run --rm app npm run lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Compose Services
        run: docker-compose build

      # Docker Composeを使ってテストを実行
      - name: Run Tests in Docker
        run: docker-compose run --rm app npm run test

      # Docker Composeのクリーンアップ
      - name: Clean up Docker Compose
        run: docker-compose down --volumes
